config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'application#index'
  get 'about' => 'application#about', as: 'about'
  get 'contact' => 'application#contact', as: 'contact'
  get 'sales' => 'application#sales', as: 'sales'

  get 'categories' => 'categories#index', as: 'categories'
  get 'categories/:id' => 'categories#show', as: 'category'

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    resources :products
    resources :users do
      resources :orders
    end

    resources :provinces

    get 'settings/about' => 'settings#about', as: 'about'
    get 'settings/contact' => 'settings#contact', as: 'contact'
    get 'settings/title' => 'settings#title', as: 'title'
    get 'settings/default_province' => 'settings#default_province', as: 'default_province'
    post 'settings/default_province' => 'settings#update_default_province',
         as: 'update_default_province'
    resources :settings

    get 'categories/children/' => 'categories#children'
    get 'categories/children/:parent_id(.:format)' => 'categories#children'
    get 'categories/except/:id(.:format)' => 'categories#except'
    resources :categories
  end

  post 'users' => 'users#create'
  get 'profile' => 'users#profile', :as => 'profile'
  get 'profile/edit' => 'users#edit', :as => 'edit_profile'

  get 'products' => 'products#index'
  get 'products/search' => 'products#search'
  get 'products/:id' => 'products#show', :as => 'product'

  get 'cart' => 'carts#show', :as => 'cart'

  get 'cart/checkout' => 'checkout#checkout', :as => 'checkout'
  post 'cart/checkout' => 'checkout#checkout_address'

  get 'cart/checkout/payment' => 'checkout#checkout_payment', :as => 'checkout_payment'
  post 'cart/checkout/payment' => 'checkout#create_payment'

  post 'account/stripe_card_token' => 'carts#stripe_card_token'

  get 'cart/checkout/complete' => 'checkout#checkout_complete', :as => 'checkout_complete'

  resources :order_items, only: [:create, :update, :destroy]

  resource :addresses, only: [:create, :update, :destroy]

  resources :sessions

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user, inverse_of: :orders
  belongs_to :order_status
  belongs_to :shipping_address, class_name: 'Address'
  belongs_to :billing_address, class_name: 'Address'

  has_one :payment, autosave: true

  has_many :order_items, dependent: :delete_all

  before_save :update_subtotal

  validates :subtotal, :tax, :shipping, presence: true, if: :paid?
  validates :shipping_address_id, :billing_address_id, presence: true, if: :paid?

  def associate_addresses!(shipping_address, billing_address)
    update(shipping_address: shipping_address, billing_address: billing_address)
  end

  def update_taxes(taxes_amount)
    self[:tax] = taxes_amount
  end

  def update_shipping_cost(shipping_amount)
    self[:shipping] = shipping_amount
  end

  def update_payment!
    payment.date = Time.now
    payment.total = total
    save
  end

  def to_s
    "##{id}"
  end

  def subtotal
    order_items.collect do |oi|
      oi.valid? ? (oi.quantity * oi.unit_price) : 0
    end.sum
  end

  def total
    subtotal + tax + shipping
  end

  def opened?
    order_status.id.equal? OrderStatus::OPENED
  end

  def open!
    order_status.id = OrderStatus.construct_status :open
  end

  def in_progress?
    order_status.id.equal? OrderStatus::IN_PROGRESS
  end

  def in_progress!
    self.order_status = OrderStatus.construct_status :in_progress
    save
  end

  def paid?
    order_status.id.equal? OrderStatus::PAID
  end

  def paid!
    self.order_status = OrderStatus.construct_status :paid
    save
  end

  def shipped?
    order_status.id.equal? OrderStatus::SHIPPED
  end

  def shipped!
    self.order_status = OrderStatus.construct_status :shipped
    save
  end

  def cancelled?
    order_status.id.equal? OrderStatus::CANCELLED
  end

  def cancel!
    self.order_status = OrderStatus.construct_status :cancel
    save
  end

  private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::AdminController
    before_action :set_admin_user_order, only: [:show, :edit, :update, :destroy]

    # GET /admin/user/:id/orders
    def index
      @user = User.find(params[:user_id])
      page = params[:page].to_i
      @orders = Order.page(page).per(10).where(user: @user)
    end

    # GET /admin/orders/1
    # GET /admin/orders/1.json
    def show
    end

    # GET /admin/orders/new
    def new
      @order = Order.new
    end

    # GET /admin/orders/1/edit
    def edit
    end

    # POST /admin/orders
    def create
      @order = Order.new(admin_order_params)
      respond_to do |format|
        if @order.save
          format.html { redirect_to [:admin, @order], notice: 'Order created.' }
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /admin/orders/1
    def update
      respond_to do |format|
        if @order.update(admin_order_params)
          format.html { redirect_to admin_order_path(@order), notice: 'Order updated.' }
          format.json { head :no_content }
        else
          format.html { render :edit }
          format.json { head :no_content }
        end
      end
    end

    # DELETE /admin/orders/1
    # DELETE /admin/orders/1.json
    def destroy
      @order.destroy
      respond_to do |format|
        format.html do
          redirect_to admin_orders_url,
                      notice: 'Order was successfully destroyed.'
        end
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user_order
      @order = Order.find(params[:id])
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def admin_order_params
      params.require(:order).permit(:order_status_id)
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin
  module OrdersHelper
  end
end

app/views/admin/orders/_form.html.erb
<%= form_for(@admin_order) do |f| %>
  <% if @admin_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_order.errors.count, "error") %> prohibited this admin_order from being saved:</h2>

      <ul>
      <% @admin_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Editing Admin Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_order %> |
<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing orders for
  user <%= "##{@user.id} - '#{@user.first_name} #{@user.last_name}'" %></h1>
<div class="text-center">
  <p><%= page_entries_info @orders %></p>
  <%= paginate @orders, :theme => 'twitter-bootstrap-3' %>
</div>
<table class="table">
  <thead>
  <tr>
    <th>#</th>
    <th>Subtotal</th>
    <th>Taxes</th>
    <th>Shipping</th>
    <th>Status</th>
    <th>Shipping address</th>
    <th>Billing address</th>
    <th colspan="2"></th>
  </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= number_to_currency order.subtotal %></td>
        <td><%= number_to_currency order.tax %></td>
        <td><%= number_to_currency order.shipping %></td>
        <% if order.paid? || order.shipped? || order.cancelled? %>
            <td>
              <%= form_for [:admin, @user, order], html: {class: 'form', remote: true}, format: :json do |f| %>
                  <%= token_tag nil %>
                  <%= f.collection_select :order_status_id, OrderStatus.where(id: [20, 30, 40]), :id, :name, {class: 'form-control'}, onchange: "this.form.submit()" %>
              <% end %>
            </td>
        <% else %>
            <td><b><%= order.order_status.name %></b></td>
        <% end %>
        <td><%= order.shipping_address %></td>
        <td><%= order.billing_address %></td>
        <td><%= link_to 'Show', admin_user_order_path(@user, order) %></td>
        <!--<td><%= link_to 'Edit', edit_admin_user_order_path(@user, order) %></td>-->
        <!--<td><%= link_to 'Destroy', [:admin, @user, order], method: :delete, data: {confirm: 'Are you sure?'} %></td>-->
      </tr>
  <% end %>
  </tbody>
</table>
<div class="text-center">
  <%= paginate @orders, :theme => 'twitter-bootstrap-3' %>
  <p><%= page_entries_info @orders %></p>
</div>
<br>

<%= link_to 'See all users', admin_users_path %>

app/views/admin/orders/new.html.erb
<h1>New Admin Order</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_orders_path %>

app/views/admin/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Order <%= @order %> for user '<%= @user.to_s %>'</h1>


<!--<p>-->
<!--<strong>Number:</strong>-->
<!--<%= @order.id %>-->
<!--</p>-->
<p>
  <strong>Subtotal:</strong>
  <%= number_to_currency @order.subtotal %>
</p>
<p>
  <strong>Taxes:</strong>
  <%= number_to_currency @order.tax %>
</p>

<p>
  <strong>Shipping price:</strong>
  <%= number_to_currency @order.shipping %>
</p>
<p>
  <strong>Total price:</strong>
  <%= number_to_currency @order.subtotal + @order.tax + @order.shipping %>
</p>

<p>
  <strong>Shipping address:</strong>
  <% if @order.shipping_address.present? %>
      <%= link_to "http://maps.google.com/?q=#{@order.shipping_address.street_line_1.gsub(/\s+/, "+").html_safe}", target: :_blank do %>
          <%= @order.shipping_address %>
      <% end %>
  <% else %>
    <p>No address yet</p>
<% end %>


<p>
  <strong>Billing address:</strong>
  <% if @order.billing_address.present? %>
      <%= link_to "http://maps.google.com/?q=#{@order.billing_address.street_line_1.gsub(/\s+/, "+").html_safe}", target: :_blank do %>
          <%= @order.billing_address %>

          <!--<img alt="Billing address" src=<%= "http://maps.googleapis.com/maps/api/staticmap?size=250x250&center=#{@order.billing_address.street_line_1.gsub(/\s+/, "+").html_safe}&zoom=14" %>/>-->
      <% end %>
  <% else %>
    <p>No address yet</p>
<% end %>



<p>
  <strong>Items:</strong>

</p>
<table class="table panel panel-default">
  <thead class="panel-heading">
  <tr>
    <th>Picture</th>
    <th>Item name</th>
  </tr>
  </thead>
  <tbody class="panel-body">
  <% @order.order_items.each do |order_item| %>

      <tr>
        <td><%= image_tag order_item.product.photo(:mini), class: 'img-thumbnail img-responsive' %></td>
        <td><%= link_to [:admin, order_item.product] do %>
              <%= order_item.product.product_name %>
          <% end %></td>
      </tr>

  <% end %>
  </tbody>
  <tfoot class="panel-footer">
  <tr>
    <td colspan="4"></td>
  </tr>
  </tfoot>
</table>
<br/>
<%= link_to 'Edit', edit_admin_user_order_path(@user, @order) %> |
<%= link_to 'Back', admin_user_orders_path(@user) %>