config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'application#index'
  get 'about' => 'application#about', as: 'about'
  get 'contact' => 'application#contact', as: 'contact'
  get 'sales' => 'application#sales', as: 'sales'

  get 'categories' => 'categories#index', as: 'categories'
  get 'categories/:id' => 'categories#show', as: 'category'

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    resources :products
    resources :users do
      resources :orders
    end

    resources :provinces

    get 'settings/about' => 'settings#about', as: 'about'
    get 'settings/contact' => 'settings#contact', as: 'contact'
    get 'settings/title' => 'settings#title', as: 'title'
    get 'settings/default_province' => 'settings#default_province', as: 'default_province'
    post 'settings/default_province' => 'settings#update_default_province',
         as: 'update_default_province'
    resources :settings

    get 'categories/children/' => 'categories#children'
    get 'categories/children/:parent_id(.:format)' => 'categories#children'
    get 'categories/except/:id(.:format)' => 'categories#except'
    resources :categories
  end

  post 'users' => 'users#create'
  get 'profile' => 'users#profile', :as => 'profile'
  get 'profile/edit' => 'users#edit', :as => 'edit_profile'

  get 'products' => 'products#index'
  get 'products/search' => 'products#search'
  get 'products/:id' => 'products#show', :as => 'product'

  get 'cart' => 'carts#show', :as => 'cart'

  get 'cart/checkout' => 'checkout#checkout', :as => 'checkout'
  post 'cart/checkout' => 'checkout#checkout_address'

  get 'cart/checkout/payment' => 'checkout#checkout_payment', :as => 'checkout_payment'
  post 'cart/checkout/payment' => 'checkout#create_payment'

  post 'account/stripe_card_token' => 'carts#stripe_card_token'

  get 'cart/checkout/complete' => 'checkout#checkout_complete', :as => 'checkout_complete'

  resources :order_items, only: [:create, :update, :destroy]

  resource :addresses, only: [:create, :update, :destroy]

  resources :sessions

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validates :key, presence: true

  def self.obtain(key)
    setting = Setting.find_by_key(key) || nil
    if setting.nil?
      ''
    else
      setting.value
    end
  end
end

app/controllers/admin/settings_controller.rb
module Admin
  class SettingsController < Admin::AdminController
    before_action :set_admin_setting, only: [:show, :edit, :update, :destroy]

    # GET /admin/settings
    # GET /admin/settings.json
    def index
      # @adm_set = Setting.all
    end

    # GET /admin/settings/1
    # GET /admin/settings/1.json
    def show
    end

    def about
      @content = Setting.find_or_create_by(key: 'about-content') { |s| s.value = '' }
    end

    def contact
      @content = Setting.find_or_create_by(key: 'contact-content') { |s| s.value = '' }
    end

    def title
      @content = Setting.find_or_create_by(key: 'title') { |s| s.value = '' }
    end

    # GET /admin/settings/new
    def new
      @adm_sets = Setting.new
    end

    # GET /admin/settings/1/edit
    def edit
    end

    # POST /admin/settings/default_province
    def update_default_province
      @setting = Setting.find_or_create_by(key: 'default-province')
      province = Province.find(params.require(:province)[:province_id])
      @setting.update(value: province.id)
    end

    # GET /admin/settings/default_province
    def default_province
    end

    # POST /admin/settings
    # POST /admin/settings.json
    def create
      @adm_sets = Setting.new(admin_setting_params)
      respond_to do |format|
        if @adm_sets.save
          format.html { redirect_to admin_setting_path(@adm_sets), notice: 'Setting created.' }
          format.json { render :show, status: :created, location: @adm_sets }
        else
          format.html { render :new }
          format.json { render json: @adm_sets.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /admin/settings/1
    # PATCH/PUT /admin/settings/1.json
    def update
      respond_to do |format|
        if @adm_sets.update(admin_setting_params)
          format.html { redirect_to [:admin, :settings], notice: 'Setting updated.' }
          format.json { render :show, status: :ok, location: @adm_sets }
        else
          format.html { render :edit }
          format.json { render json: @adm_sets.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /admin/settings/1
    # DELETE /admin/settings/1.json
    def destroy
      @adm_sets.destroy
      respond_to do |format|
        format.html { redirect_to admin_settings_url, notice: 'Setting destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_setting
      id = params[:id].to_i

      if id != 0
        @adm_sets = Setting.find(id)
      else
        @adm_sets = Setting.find_by_key(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_setting_params
      params.require(:setting).permit(:key, :value)
    end
  end
end

app/helpers/admin/settings_helper.rb
module Admin
  module SettingsHelper
  end
end

app/views/admin/settings/_form.html.erb
<%= form_for [:admin, @admin_setting] do |f| %>
  <% if @admin_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_setting.errors.count, "error") %> prohibited this admin_setting from being saved:</h2>

      <ul>
      <% @admin_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/settings/about.html.erb
<%= form_for [:admin, @content] do |f| -%>

    <%= f.cktext_area :value %>
    <br>
    <%= f.submit "Save changes", class: 'btn btn-success btn-block' %>
    <%= link_to 'Cancel', :back , class: 'btn btn-default btn-block' %>
<% end -%>

app/views/admin/settings/contact.html.erb
<%= form_for [:admin, @content] do |f| -%>

    <%= f.cktext_area :value %>
    <br>
    <%= f.submit "Save changes", class: 'btn btn-success btn-block' %>
    <%= link_to 'Cancel', :back , class: 'btn btn-default btn-block' %>
<% end -%>

app/views/admin/settings/edit.html.erb
<h1>Editing Admin Setting</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @admin_setting] %> |
<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>General website settings</h1>

<p><%= link_to 'About page',[:admin, :about] %></p>
<p><%= link_to 'Contact page',[:admin, :contact] %></p>
<p><%= link_to 'Website title',[:admin, :title] %></p>

app/views/admin/settings/new.html.erb
<h1>New Admin Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/show.html.erb
<p id="notice"><%= notice %></p>
<% debug @admin_setting %>
<p>
  <strong>Key:</strong>
  <%= @admin_setting.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @admin_setting.value %>
</p>

<%= link_to 'Edit', edit_admin_setting_path(@admin_setting) %> |
<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/title.html.erb
<%= form_for [:admin, @content] do |f| -%>

    <%= f.text_area :value %>
    <br>
    <%= f.submit "Save changes", class: 'btn btn-success btn-block' %>
    <%= link_to 'Cancel', :back , class: 'btn btn-default btn-block' %>
<% end -%>

app/views/admin/settings/update_default_province.js.erb
<% button_id = "#set_province_#{@setting.value}" %>

actualButton = $(".btn-info");
$(actualButton).removeClass('disabled');
$(actualButton).removeAttr('disabled');
$(actualButton).addClass('btn-default');
$(actualButton).removeClass('btn-info');

button = $("<%= button_id %>");
$(button).addClass('disabled');
$(button).attr('disabled');
$(button).removeClass('btn-default');
$(button).addClass('btn-info');