config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'application#index'
  get 'about' => 'application#about', as: 'about'
  get 'contact' => 'application#contact', as: 'contact'
  get 'sales' => 'application#sales', as: 'sales'

  get 'categories' => 'categories#index', as: 'categories'
  get 'categories/:id' => 'categories#show', as: 'category'

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    resources :products
    resources :users do
      resources :orders
    end

    resources :provinces

    get 'settings/about' => 'settings#about', as: 'about'
    get 'settings/contact' => 'settings#contact', as: 'contact'
    get 'settings/title' => 'settings#title', as: 'title'
    get 'settings/default_province' => 'settings#default_province', as: 'default_province'
    post 'settings/default_province' => 'settings#update_default_province',
         as: 'update_default_province'
    resources :settings

    get 'categories/children/' => 'categories#children'
    get 'categories/children/:parent_id(.:format)' => 'categories#children'
    get 'categories/except/:id(.:format)' => 'categories#except'
    resources :categories
  end

  post 'users' => 'users#create'
  get 'profile' => 'users#profile', :as => 'profile'
  get 'profile/edit' => 'users#edit', :as => 'edit_profile'

  get 'products' => 'products#index'
  get 'products/search' => 'products#search'
  get 'products/:id' => 'products#show', :as => 'product'

  get 'cart' => 'carts#show', :as => 'cart'

  get 'cart/checkout' => 'checkout#checkout', :as => 'checkout'
  post 'cart/checkout' => 'checkout#checkout_address'

  get 'cart/checkout/payment' => 'checkout#checkout_payment', :as => 'checkout_payment'
  post 'cart/checkout/payment' => 'checkout#create_payment'

  post 'account/stripe_card_token' => 'carts#stripe_card_token'

  get 'cart/checkout/complete' => 'checkout#checkout_complete', :as => 'checkout_complete'

  resources :order_items, only: [:create, :update, :destroy]

  resource :addresses, only: [:create, :update, :destroy]

  resources :sessions

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  attr_accessor :image_delete

  # In case that a new style has to be added
  # look that page:
  # https://github.com/thoughtbot/paperclip/wiki/Thumbnail-Generation
  has_attached_file :photo,
                    styles:
                        { mini: '80x80>', small: '150x150>' },
                    url:
                        '/assets/products/:id/:style/:basename.:extension',
                    path:
                        ':rails_root/public/assets/products/'\
                        ':id/:style/:basename.:extension',
                    default_url:
                        '/images/no_picture.png'

  # has_destroyable_file :photo

  has_many :order_items

  # default_scope { where(active: true) }

  # validates_attachment_presence :photo
  validates_attachment_size :photo,
                            less_than: 5.megabytes

  validates_attachment_content_type :photo,
                                    content_type: ['image/jpeg', 'image/png']

  # Validations
  validates :product_name, :short_description, :category, :unit_price,
            :quantity_per_unit, :unit_weight, presence: true

  before_save { delete_photo if image_delete == '1' }

  # Search indexing

  searchable do
    text :product_name, :product_long_description

    integer :category_id,
            multiple: true,
            references: Category

    double :discount
    double :price

    boolean :product_available
    boolean :discount_available
    boost { :discount_available ? 2.0 : 1.0 }

    time :created_at
    time :updated_at
  end

  def price_discount
    price - discount
  end

  def price
    unit_price * quantity_per_unit
  end

  protected

  def delete_photo
    photo.clear
  end

  def self.search_product(search_expression, category, options = nil)
    Product.search do
      # ============= Searching and boosting

      fulltext search_expression do
        # if the search terms are close related in the product name
        phrase_fields product_name: 2.0
        # if the search terms are present, but not necessarily very related
        boost_fields product_name: 1.5
        # boost(5.0) do
        #   with(:discount_available, true)
        # end if options[:with_discount].present?
      end
      with :product_available, true

      # ============= Filtering

      apply_filters.call(self, category, options)

      # ============= Sorting

      sort_search.call(self, options)

      # ============= Paginating
      paginate page: options[:page], per_page: 5
    end
  end

  def self.sort_search
    lambda do |context, options|
      context.order_by(:discount, :desc) if options[:with_discount].present?
      context.order_by(:updated_at, :asc)
    end
  end

  def self.apply_filters
    lambda do |context, category, options|
      apply_price_filters.call(context, options)

      apply_product_filters.call(context, options)

      apply_category_filters.call(context, category)
    end
  end

  def self.apply_price_filters
    lambda do |context, options|
      options[:minimum_price].present? && context.with(:price)\
        .greater_than_or_equal_to(options[:minimum_price].to_i)
      options[:maximum_price].present? && context.with(:price)\
        .less_than_or_equal_to(options[:maximum_price].to_i)
    end
  end

  def self.apply_category_filters
    lambda do |context, category|
      # ============= Filtering category
      # It is important to also consider all the descendant categories from
      # the current one. This is why we must fill the second parameter of
      # 'with' with the children ids as well the own category id (!)
      category && context.with(:category_id, category.child_ids << category.id)
    end
  end

  def self.apply_product_filters
    lambda do |context, options|
      options[:offers_only].present? && context.with(:discount_available, true)
      options[:new_products].present? && context\
        .with(:created_at).greater_than_or_equal_to(Time.now - 1.day)
    end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::AdminController
    before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

    # GET /admin/products
    # GET /admin/products.json
    def index
      page = params[:page].to_i
      @admin_products = Product.page(page).per(10)
    end

    # GET /admin/products/1
    # GET /admin/products/1.json
    def show
    end

    # GET /admin/products/new
    def new
      @product = Product.new
    end

    # GET /admin/products/1/edit
    def edit
    end

    # POST /admin/products
    def create
      @product = Product.new(admin_product_params)
      respond_to do |format|
        if @product.save
          format.html { redirect_to [:admin, @product], notice: 'Product created.' }
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /admin/products/1
    def update
      respond_to do |format|
        if @product.update(admin_product_params)
          format.html do
            redirect_to admin_product_path(@product),
                        notice: 'Product was successfully updated.'
          end
        else
          format.html { render :edit }

        end
      end
    end

    # DELETE /admin/products/1
    # DELETE /admin/products/1.json
    def destroy
      @product.destroy
      respond_to do |format|
        format.html do
          redirect_to admin_products_url,
                      notice: 'Product was successfully destroyed.'
        end
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def admin_product_params
      params.require(:product).permit(:product_name,
                                      :short_description,
                                      :product_long_description,
                                      :category_id,
                                      :quantity_per_unit,
                                      :unit_price, :discount,
                                      :discount_available,
                                      :unit_weight, :unit_in_stock,
                                      :product_available, :picture_url,
                                      :photo, :image_delete)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < CustomerController
  before_action :redirect_admin

  # GET /products
  # GET /products.json
  def index
    redirect_to :root
    # @products = Product.where(product_available: true)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = product

    @category = @product.category
    mount_breadcrumbs_show

    @order_item = current_order.order_items.new

    render 'not_available' unless @product.product_available?
  end

  def mount_breadcrumbs_show
    path = @category.path.from_depth(1)
    path.each do |category|
      add_breadcrumb category.name, category
    end
    add_breadcrumb @product.product_name
  end

  # GET /products/search
  # GET /products/search.json
  # GET /products/search.xml
  def search
    add_breadcrumb 'Search results'

    # Replaces commas by spaces. Removes initial and final spaces before.
    search_expression = filter_search_terms
    @search_terms = search_expression.split(' ')

    @products = Product.search_product search_expression, category, params
    respond_to do |format|
      format.html { render action: 'search_results' }
      format.json { render json: @products }
    end
  end

  private

  def filter_search_terms
    params[:search].lstrip.rstrip.gsub(',', ' ')
  end

  def product
    Product.find(params[:id])
  end

  def category
    Category.find(params[:category]) if params[:category].present?
  end
end

app/helpers/admin/products_helper.rb
module Admin
  module ProductsHelper
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], :html => {:multipart => true, class: 'form'} do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this admin_product
            from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :product_name %><br>
      <%= f.text_field :product_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :short_description %><br>
      <%= f.text_area :short_description, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :product_long_description %><br>
      <%= f.text_area :product_long_description, class: 'form-control', rows: 10 %>
    </div>
    <div class="form-group">
      <%= f.label :category_id %><br>
      <%= grouped_collection_select(
                  :product, #The instance of the class to be used for the select tag
                  :category_id, #The attribute of object corresponding to the select tag
                  Category.primary_categories, #An array of objects representing the <optgroup> tags.
                  :children, #The method to be called on each of the elements above to generate the children
                  :name, #Name from group element to be used as the value for the <optgroup>
                  :id, #The name of a method which, when called on a child object of a member of collection, returns a value to be used as the value attribute for its <option> tag.
                  :name, #The name of a method which, when called on a child object of a member of collection, returns a value to be used as the contents of its <option> tag.
                  class: 'form-control'

          )
          #documentation http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-grouped_collection_select
      %>
    </div>
    <div class="form-group">
      <%= f.label :quantity_per_unit %><br>
      <%= f.number_field :quantity_per_unit, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :unit_price %><br>
      <%= f.text_field :unit_price, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :discount %><br>
      <%= f.text_field :discount, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :discount_available %><br>
      <%= f.check_box :discount_available %>
    </div>
    <div class="form-group">
      <%= f.label :unit_weight %> (g)<br>
      <%= f.number_field :unit_weight, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :unit_in_stock %><br>
      <%= f.number_field :unit_in_stock, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :product_available %><br>
      <%= f.check_box :product_available %>
    </div>
    <% if @product.photo? %>
        <div class="form-group">
          <%= f.label :image_delete, 'Delete image' %><br>
          <%= f.check_box :image_delete %>
        </div>
    <% end %>
    <div id="photo_field" class="form-group">
      <%= f.label :photo %><br>
      <%= f.file_field :photo, class: 'form-control' %>
      <%= image_tag @product.photo(:small), class: 'img-rounded' %>
    </div>
    <div class="actions">
      <%= f.submit class: 'btn btn-success' %>
    </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product <%= @product.product_name %></h1>

<%= render 'form' %>
<br/>
<%= link_to 'Show', [:admin, @product] %> |
<%= link_to 'Back', admin_products_path, class: 'btn btn-default', role: :button %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Products</h1>
<div class="text-center">
  <p><%= page_entries_info @admin_products %></p>
  <%= paginate @admin_products, :theme => 'twitter-bootstrap-3' %>
</div>
<div class="panel panel-default">
  <table class="table table-hover">
    <thead class="panel-heading">
    <tr>
      <th>Product name</th>
      <!--<th>Short description</th>-->
      <th>Product description</th>
      <th>Category</th>
      <th>Quantity per unit</th>
      <th>Unit price</th>
      <th>Discount</th>
      <th>Discount available</th>
      <th>Unit weight</th>
      <th>Unit in stock</th>
      <th>Product available</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody class="panel-body">
    <% @admin_products.each do |admin_product| %>
        <tr>
          <td><%= admin_product.product_name %></td>
          <!--<td><%= admin_product.short_description %></td>-->
          <td><%= admin_product.product_long_description %></td>
          <td><%= admin_product.category.name %></td>
          <td><%= admin_product.quantity_per_unit %></td>
          <td><%= number_to_currency(admin_product.unit_price) %></td>
          <td><%= number_to_currency(admin_product.discount) %></td>
          <td>
            <% if admin_product.discount_available %>
                <i class="fa fa-check-circle"></i>
            <% else %>
                <i class="fa fa-times-circle"></i>
            <% end %>
          </td>
          <td><%= admin_product.unit_weight %> g</td>
          <td><%= admin_product.unit_in_stock %></td>
          <td>
            <% if admin_product.product_available %>
                <i class="fa fa-check-circle"></i>
            <% else %>
                <i class="fa fa-times-circle"></i>
            <% end %>
          </td>
          <td><%= image_tag admin_product.photo(:small), class: 'img-thumbnail' %></td>

          <td><%= link_to 'Show', admin_product_path(admin_product) %></td>
          <td><%= link_to 'Edit', edit_admin_product_path(admin_product) %></td>
          <td><%= link_to 'Destroy', [:admin, admin_product], method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
    <tfoot class="panel-footer">
    <tr>
      <td colspan="15"></td>
    </tr>
    </tfoot>
  </table>
</div>
<div class="text-center">
  <%= paginate @admin_products, :theme => 'twitter-bootstrap-3' %>
  <p><%= page_entries_info @admin_products %></p>
</div>
<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Back', admin_products_path, class: 'btn btn-default', role: :button %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Product display</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6">
      <div class="well well-sm">
        <div class="row">
          <div class="col-sm-6 col-md-4">
            <%= image_tag @product.photo, class: 'img-rounded img-responsive' %>
            <!--<img src="http://placehold.it/380x500" alt="" class="img-rounded img-responsive" />-->
          </div>
          <div class="col-sm-6 col-md-8">
            <h4><%= @product.product_name %></h4>

            <p>
              <strong>Product short description:</strong>
              <%= @product.short_description %>
            </p>
            <p>
              <strong>Product description:</strong>
              <%= @product.product_long_description %>
            </p>

            <p>
              <strong>Category:</strong>
              <%=
                  @product.category.path.from_depth(1).first.name
              %>
            </p>

            <p>
              <strong>Sub-Category:</strong>
              <%=
                  @product.category.path.from_depth(1).last.name
              %>
            </p>

            <p>
              <strong>Quantity per unit:</strong>
              <%= @product.quantity_per_unit %>
            </p>

            <p>
              <strong>Unit price:</strong>
              <%= number_to_currency(@product.unit_price) %>
            </p>

            <p>
              <strong>Discount:</strong>
              <%= number_to_currency(@product.discount) %>
            </p>

            <p>
              <strong>Discount available:</strong>
              <% if @product.discount_available %>
                  <i class="fa fa-check-circle"></i>
              <% else %>
                  <i class="fa fa-times-circle"></i>
              <% end %>
            </p>

            <p>
              <strong>Unit weight (g):</strong>
              <%= @product.unit_weight %>
            </p>

            <p>
              <strong>Unit in stock:</strong>
              <%= @product.unit_in_stock %>
            </p>

            <p>
              <strong>Product available:</strong>
              <% if @product.product_available %>
                  <i class="fa fa-check-circle"></i>
              <% else %>
                  <i class="fa fa-times-circle"></i>
              <% end %>
            </p>
            <!-- Split button -->

            <div class="btn-group">
              <%= link_to 'Edit', edit_admin_product_path(@product), class: 'btn btn-success' %>
              <%= link_to 'Back', admin_products_path, class: 'btn btn-default' %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% if false %>
    <p>
      <strong>Product name:</strong>
      <%= @product.product_name %>
    </p>

    <p>
      <strong>Product description:</strong>
      <%= @product.product_description %>
    </p>

    <p>
      <strong>Category:</strong>
      <%=
          @product.category.path.from_depth(1).first.name
      %>
    </p><p>
  <strong>Sub-Category:</strong>
  <%=
      @product.category.path.from_depth(1).last.name
  %>
</p>

    <p>
      <strong>Quantity per unit:</strong>
      <%= @product.quantity_per_unit %> g
    </p>

    <p>
      <strong>Unit price:</strong>
      <%= number_to_currency(@product.unit_price) %>
    </p>

    <p>
      <strong>Discount:</strong>
      <%= @product.discount %>
    </p>

    <p>
      <strong>Discount available:</strong>
      <%= @product.discount_available %>
    </p>

    <p>
      <strong>Unit weight:</strong>
      <%= @product.unit_weight %>
    </p>

    <p>
      <strong>Unit in stock:</strong>
      <%= @product.unit_in_stock %>
    </p>

    <p>
      <strong>Product available:</strong>
      <%= @product.product_available %>
    </p>
    <div>
      <strong>Photo</strong>
      <%= image_tag @product.photo, class: 'img-rounded' %>
    </div>

    <%= link_to 'Edit', edit_admin_product_path(@product) %> |
    <%= link_to 'Back', admin_products_path %>
<% end %>